## **RA1: table 221116**

Dong Gyun Ko <br>

last updated: november 16, 2022 <br>

In [1]:
# import libraries

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import datetime as dt
import os
import warnings
import requests # python 3.6

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
# set the working directory

os.chdir('/content/gdrive/MyDrive/Colab Notebooks/RA1_data')

## **1. import data_221115**

In [3]:
# import the data

data_221115 = pd.read_excel('data_221115.xlsx')
data_221115['quarter'] = pd.to_datetime(data_221115['quarter'])
data_221115['quarter'] = data_221115['quarter'].dt.to_period('Q')

In [4]:
# quarterly dataset 221020

data_221115 = data_221115.sort_values(by=['isocode', 'quarter']).drop(columns=['Unnamed: 0']).reset_index(drop=True)

data_221115

,country,isocode,quarter,region,income,oecd,g7,tradeopen,finopen_ci,finopen_ci_n,...,fxflex_fine,fxflex_coarse,ggdebt,ggcon,gdp,reer,ca,pcon,cds,inv
0,Argentina,ARG,1950Q1,7,2,NaN,NaN,NaN,NaN,NaN,...,14.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,ARG,1950Q2,7,2,NaN,NaN,NaN,NaN,NaN,...,14.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Argentina,ARG,1950Q3,7,2,NaN,NaN,NaN,NaN,NaN,...,14.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Argentina,ARG,1950Q4,7,2,NaN,NaN,NaN,NaN,NaN,...,14.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,ARG,1951Q1,7,2,NaN,NaN,NaN,NaN,NaN,...,14.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14495,South Africa,ZAF,2021Q2,5,2,NaN,NaN,55.219369,NaN,NaN,...,NaN,NaN,70.881640,2.236984e+11,1.165743e+12,80.196367,5.043574,7.696255e+11,187.5187,1.624898e+11
14496,South Africa,ZAF,2021Q3,5,2,NaN,NaN,57.412444,NaN,NaN,...,NaN,NaN,70.725171,2.239592e+11,1.124135e+12,78.671305,2.392012,7.426943e+11,215.0529,1.596462e+11
14497,South Africa,ZAF,2021Q4,5,2,NaN,NaN,59.447237,NaN,NaN,...,NaN,NaN,71.314406,2.240916e+11,1.125567e+12,75.720268,3.023261,7.469260e+11,205.5150,1.571342e+11
14498,South Africa,ZAF,2022Q1,5,2,NaN,NaN,61.192979,NaN,NaN,...,NaN,NaN,NaN,2.258330e+11,1.137366e+12,76.993295,2.612085,7.557754e+11,211.3849,1.615184e+11
14499,South Africa,ZAF,2022Q2,5,2,NaN,NaN,63.724656,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,77.986125,NaN,7.539543e+11,319.0284,1.614398e+11

## **2. python code**

In [5]:
data_221115.columns

Index(['country', 'isocode', 'quarter', 'region', 'income', 'oecd', 'g7',
       'tradeopen', 'finopen_ci', 'finopen_ci_n', 'finopen_fa', 'fxflex_fine',
       'fxflex_coarse', 'ggdebt', 'ggcon', 'gdp', 'reer', 'ca', 'pcon', 'cds',
       'inv'],
      dtype='object')

In [6]:
# stat function generating the summary statistics by isocode

# import data_221115 as data
data = data_221115

# stat function
def stat(var):

    for i in range(0, data['isocode'].unique().shape[0]):
  
        globals()['cond_isocode_{}'.format(i+1)] = (data['isocode'] == data['isocode'].unique()[i])
        globals()['df_isocode_{}'.format(i+1)] = data.loc[globals()['cond_isocode_{}'.format(i+1)]]
        globals()['df_isocode_count_T_{}'.format(i+1)] = globals()['df_isocode_{}'.format(i+1)].groupby(globals()['df_isocode_{}'.format(i+1)]['quarter']).count()

        globals()['cond_{}'.format(var) + '_{}'.format(i+1)] = (globals()['df_isocode_count_T_{}'.format(i+1)][var] == 0)
        globals()['df_isocode_count_T_{}'.format(i+1)] = globals()['df_isocode_count_T_{}'.format(i+1)].loc[~globals()['cond_{}'.format(var) + '_{}'.format(i+1)]]
        globals()['df_isocode_count_T_{}'.format(i+1)] = globals()['df_isocode_count_T_{}'.format(i+1)].reset_index()

        # missing
        if globals()['df_isocode_count_T_{}'.format(i+1)]['quarter'].unique().shape[0] == 0:

           globals()['tab_stat_{}'.format(var) + '_{}'.format(i+1)] = pd.DataFrame(np.array([data['country'].unique()[i], 
                                                                                             data['isocode'].unique()[i], 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan, 
                                                                                             np.nan]).reshape(1, -1)
                                                                                             ).rename(columns={0: 'country', 
                                                                                                               1: 'isocode', 
                                                                                                               2: 'obs', 
                                                                                                               3: 'mean', 
                                                                                                               4: 'std', 
                                                                                                               5: 'min', 
                                                                                                               6: '25th', 
                                                                                                               7: 'median', 
                                                                                                               8: '75th', 
                                                                                                               9: 'max'}).reset_index(drop=True)

        # observed
        else:

           globals()['tab_stat_{}'.format(var) + '_{}'.format(i+1)] = pd.DataFrame(np.array([data['country'].unique()[i], 
                                                                                             data['isocode'].unique()[i], 
                                                                                             int(globals()['df_isocode_{}'.format(i+1)][var].describe()[0]), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[1], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[2], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[3], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[4], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[5], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[6], 2), 
                                                                                             np.round(globals()['df_isocode_{}'.format(i+1)][var].describe()[7], 2)]).reshape(1, -1)
                                                                                             ).rename(columns={0: 'country', 
                                                                                                               1: 'isocode', 
                                                                                                               2: 'obs', 
                                                                                                               3: 'mean', 
                                                                                                               4: 'std', 
                                                                                                               5: 'min', 
                                                                                                               6: '25th', 
                                                                                                               7: 'median', 
                                                                                                               8: '75th', 
                                                                                                               9: 'max'}).reset_index(drop=True)

    globals()['tab_stat_{}'.format(var)] = pd.concat([globals()['tab_stat_{}'.format(var) + '_{}'.format(1)], globals()['tab_stat_{}'.format(var) + '_{}'.format(2)]])

    for j in range(3, data['isocode'].unique().shape[0]+1):
        
        globals()['tab_stat_{}'.format(var)] = pd.concat([globals()['tab_stat_{}'.format(var)], globals()['tab_stat_{}'.format(var) + '_{}'.format(j)]])

    globals()['tab_stat_{}'.format(var)] = pd.DataFrame(globals()['tab_stat_{}'.format(var)]).reset_index(drop=True)

    return globals()['tab_stat_{}'.format(var)]

## **3. summary stat. table**

### **3.1. tab_stat_ggdebt_221116**

In [7]:
stat('ggdebt')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,117,63.1,31.45,26.1,38.77,53.95,84.72,157.87
1,Australia,AUS,135,24.97,11.41,8.32,15.3,24.44,33.04,55.08
2,Austria,AUT,89,76.37,6.44,65.63,69.7,74.76,82.56,87.11
3,Belgium,BEL,108,108.68,11.05,89.29,102.32,107.13,112.08,134.79
4,Bulgaria,BGR,89,28.94,17.08,12.89,16.53,23.85,29.49,77.2
5,Brazil,BRA,96,68.68,11.91,38.41,60.67,64.96,75.11,97.52
6,Canada,CAN,128,80.08,12.29,55.52,73.45,79.68,88.54,107.97
7,Switzerland,CHE,109,35.52,7.79,25.31,28.42,32.23,43.73,47.04
8,Chile,CHL,96,17.99,8.29,7.31,11.32,15.62,23.23,38.81
9,Colombia,COL,101,38.09,12.57,12.7,32.57,35.52,44.72,70.22
10,Cyprus,CYP,89,78.14,22.59,44.75,58.81,65.16,103.53,120.13
11,Czech Republic,CZE,93,32.37,8.34,14.53,27.4,32.26,38.99,44.71
12,Germany,DEU,94,67.79,6.92,57.98,61.75,66.82,72.55,81.05
13,Denmark,DNK,89,41.37,7.13,25.81,35.73,42.35,45.76,57.79
14,Spain,ESP,108,71.85,26.26,35.02,51.09,62.74,101.67,123.18
15,Estonia,EST,89,8.01,4.07,3.68,5.08,6.72,9.66,20.96
16,Finland,FIN,89,53.16,12.71,32.53,42.37,49.04,65.44,75.64
17,France,FRA,89,83.15,17.92,58.22,65.8,86.43,98.1,117.44
18,United Kingdom,GBR,224,54.0,19.59,27.58,39.84,44.36,70.53,104.0
19,Greece,GRC,89,144.57,37.21,100.77,104.59,148.47,178.71,211.41
20,"Hong Kong SAR, China",HKG,92,47.52,23.4,15.88,22.6,58.9,66.98,85.34
21,Croatia,HRV,106,53.14,21.87,20.75,36.64,41.56,74.91,90.81
22,Hungary,HUN,205,62.65,13.94,26.81,56.45,61.59,74.06,89.93
23,Indonesia,IDN,81,35.5,13.01,22.82,25.91,29.98,41.06,71.68
24,India,IND,164,70.18,8.53,48.0,66.86,69.64,73.64,87.42
25,Ireland,IRL,90,61.14,30.85,23.81,31.38,59.17,77.41,124.71
26,Israel,ISR,118,80.99,16.73,59.34,68.12,77.51,92.66,121.89
27,Italy,ITA,106,122.44,14.23,104.81,109.53,118.62,135.51,159.41
28,Japan,JPN,97,162.53,38.52,81.79,138.54,164.43,197.47,227.18
29,"Korea, Rep.",KOR,125,21.35,13.8,4.7,7.48,21.17,35.02,46.58
30,Lithuania,LTU,90,30.23,9.96,13.88,21.29,34.14,38.92,47.46
31,Luxembourg,LUX,89,15.82,6.97,6.95,7.68,19.31,21.6,28.11
32,Latvia,LVA,89,28.93,14.26,7.83,13.27,36.78,41.3,47.71
33,Mexico,MEX,125,27.18,6.83,18.51,20.74,27.03,32.68,42.0
34,Malta,MLT,86,61.31,8.11,41.53,57.2,63.7,67.66,71.22
35,Netherlands,NLD,90,55.55,6.96,42.56,50.39,53.91,60.1,68.6
36,Norway,NOR,89,37.5,6.75,23.55,31.4,37.56,42.51,51.43
37,New Zealand,NZL,129,29.41,6.28,15.95,26.37,29.6,33.38,47.69
38,Poland,POL,89,48.96,5.51,35.7,46.11,49.58,53.54,59.51
39,Portugal,PRT,90,98.34,30.94,54.03,68.94,102.4,131.01,138.66
40,Romania,ROU,89,28.7,10.54,10.74,21.69,29.7,36.93,48.89
41,Russian Federation,RUS,97,30.31,33.44,7.15,11.29,15.72,32.45,157.71
42,Singapore,SGP,128,93.47,18.59,67.58,79.01,94.94,101.89,149.36
43,Slovak Republic,SVK,89,46.41,9.46,26.38,38.94,49.88,52.83,63.4
44,Slovenia,SVN,90,48.79,23.49,21.7,26.65,41.45,75.47,84.72
45,Sweden,SWE,106,45.67,9.87,34.53,37.94,42.22,49.52,67.3
46,Thailand,THA,100,27.01,8.6,3.7,23.53,27.21,30.7,52.98
47,Turkiye,TUR,84,42.33,14.3,26.8,31.23,38.57,48.73,78.24
48,United States,USA,288,60.87,19.81,35.95,45.85,57.27,66.45,123.34
49,South Africa,ZAF,245,40.41,8.97,25.18,32.25,39.87,46.17,71.44

### **3.2. tab_stat_ggcon_221116**

In [8]:
stat('ggcon')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,73,20452812392.3,3571145245.95,13033694825.83,17490165308.69,21576512401.71,23560151173.85,24855464029.54
1,Australia,AUS,251,45310832720.7,27136912325.94,9692321635.47,23269698636.0,39958599533.1,64932293770.32,117995575822.65
2,Austria,AUT,110,14407493150.62,1704250862.7,11525774176.08,12820434188.61,14881143402.53,15533737776.76,18363273149.89
3,Belgium,BEL,109,20495126887.28,2210588038.82,16390858208.32,18666183267.12,21191253080.75,22245910279.9,24740739638.78
4,Bulgaria,BGR,109,3139119437.52,470694880.86,1915913323.92,2859660880.31,3161251390.45,3305711395.8,4192832643.68
5,Brazil,BRA,105,47661305783.8,6896868151.56,35419721945.16,40918266960.89,49471722552.44,54330913247.39,55690820327.98
6,Canada,CAN,245,67163154430.42,23650625997.96,23020577535.6,51395394554.5,68541736868.57,85311439329.9,114014821467.11
7,Switzerland,CHE,169,15028584121.44,3083712448.44,9283416742.79,13295902147.83,15139591120.75,17643772573.5,20975651282.01
8,Chile,CHL,106,4973085385407.32,1435600102963.49,3099683761110.11,3580324178206.66,4830464930346.66,6222085864036.0,7988066442308.78
9,Colombia,COL,69,27190933386106.3,6706078761544.45,17136560724053.84,21005615051360.25,27608254373876.13,32164609784093.08,40945545886820.66
10,Cyprus,CYP,109,768527138.3,180271247.05,420799756.35,647323075.75,792130787.88,878469053.19,1188848792.11
11,Czech Republic,CZE,105,195864115323.11,22317900324.06,156470805331.4,184487888102.38,196405275689.1,205516725661.25,244131008191.82
12,Germany,DEU,125,120157388666.25,18779586646.94,87507037702.54,107243095008.24,114051382944.2,132008358914.88,162113758359.91
13,Denmark,DNK,109,115700843224.7,13188469971.47,89880037089.35,105752344094.2,119308188301.26,127934783549.41,135875175985.05
14,Spain,ESP,110,46489469252.36,9693321023.87,29958619110.77,36912151090.8,51521830501.36,54230907325.31,59832963145.13
15,Estonia,EST,110,46491.51,9694.6,29940.86,36892.22,51475.69,54265.27,59794.78
16,Finland,FIN,129,10395773817.61,1192858234.72,8317859292.16,9266598569.19,10679059028.66,11325010251.96,12556998556.26
17,France,FRA,170,103485188033.96,20722302048.09,64562611020.54,87069352407.94,102805529100.94,121033027477.89,140611074478.75
18,United Kingdom,GBR,270,66480902324.15,22552065281.12,34320445479.84,47826513734.99,60698943161.81,86542230722.69,119964731384.37
19,Greece,GRC,109,11639000862.4,1647875341.69,9863393215.54,10412524684.99,10883545397.13,12480705041.68,15699196644.43
20,"Hong Kong SAR, China",HKG,129,55552711171.7,14937566513.1,29086896173.72,43893415521.11,53139478305.23,64596697784.07,92184242997.9
21,Croatia,HRV,109,16645693789.35,2285498201.78,13184833178.29,14361059961.65,17577744175.86,18042098622.09,22004164487.83
22,Hungary,HUN,109,1462159482725.04,191235375143.04,1157069737622.62,1294874972553.21,1465742347843.4,1598342100666.86,1848519923251.27
23,Indonesia,IDN,130,124637201150959.44,72728200145779.97,40910313571290.72,54220686477080.34,103385844421703.1,199755611641494.4,251067293692856.7
24,India,IND,104,2138279820194.32,953032220667.06,864656872344.47,1277748222202.12,2012983866655.83,2814467430847.54,4063455758925.48
25,Ireland,IRL,109,7414070805.59,1696656449.65,4167604096.31,6675742454.86,7585943567.95,8316298656.92,11247940309.45
26,Israel,ISR,110,55881548758.65,12041946384.79,39465623648.37,47037425792.5,51761096652.52,64354279143.85,80900455235.54
27,Italy,ITA,105,78058492370.12,3780882255.93,69377256756.61,77762313219.0,78515391146.59,80729902226.84,83074308844.54
28,Japan,JPN,114,23712339595721.49,3056653163270.72,17781185241921.3,21569724062748.34,23422337736357.03,26287626412522.7,29339977228604.42
29,"Korea, Rep.",KOR,250,27047286236875.12,23306661972258.82,2955745695762.81,7741724947967.3,19897572246785.24,41721037564611.36,87949005181181.47
30,Lithuania,LTU,109,1350279429.75,99845143.61,1126563493.35,1248898532.38,1403910364.95,1420978349.94,1470159386.62
31,Luxembourg,LUX,109,1604842780.43,395208673.06,1002441838.53,1322023874.88,1530675629.74,1880417344.07,2482561598.41
32,Latvia,LVA,109,883119391.03,118465513.83,653219328.52,794546866.31,876837365.28,984377054.86,1122906089.57
33,Mexico,MEX,117,448209509461.08,65929651747.58,348173630973.05,400912692368.13,429559483535.05,514422490304.16,556006323822.75
34,Malta,MLT,89,357309157.36,89790820.94,261926820.53,284184276.82,334322767.06,376626899.8,598763091.03
35,Netherlands,NLD,106,37916430844.74,5932035236.11,26537479031.36,33425801056.39,41060945193.76,41909442862.21,47935209243.07
36,Norway,NOR,178,109039693126.22,33821235954.28,55133562179.53,75168775115.79,108294163809.97,138986573072.16,168772317305.32
37,New Zealand,NZL,140,8481705287.55,2414721305.51,5532033966.6,6278895888.97,7942190158.76,10034778053.11,15128267434.72
38,Poland,POL,109,63517262790.14,14857549838.38,39992091817.99,51067706015.06,65932270020.76,73268262787.95,93711272846.63
39,Portugal,PRT,109,8411580127.83,770071958.99,6443856088.87,8295482619.09,8540501628.2,9017617769.81,9418122794.15
40,Romania,ROU,109,21667769593.98,2746440004.59,11190301226.76,19959915660.63,21470701390.42,23296614716.7,26987564943.45
41,Russian Federation,RUS,75,4017185277251.12,188153181915.73,3614350576025.93,3921406647899.88,4041174323247.58,4121498010504.03,4394097947278.06
42,Singapore,SGP,186,5327361764.15,3813883239.58,880021302.6,2045691463.79,4325386728.49,8162002084.25,14292230876.39
43,Slovak Republic,SVK,109,2996817420.69,532984186.48,2118179257.67,2458440956.78,3084259058.31,3484006068.53,3927162451.84
44,Slovenia,SVN,110,1683264339.9,261887129.2,1161614901.04,1475583477.32,1767922431.2,1856267382.64,2151372763.5
45,Sweden,SWE,117,220308111927.47,20222258469.33,193328114656.62,204096533407.23,214114036507.06,237895812101.64,255064726026.46
46,Thailand,THA,116,368972966706.52,156815229009.09,151800159622.03,222090683713.38,338445755905.19,505222148834.89,660800257779.99
47,Turkiye,TUR,97,45103142537.0,15386704743.56,24158373367.91,30633079115.9,42743175317.96,57542325765.16,72555893360.29
48,United States,USA,270,391037835762.89,157481770779.5,138080474940.35,287284041197.93,379644229439.15,548856175780.0,658016053934.02
49,South Africa,ZAF,117,170044200260.3,38582833720.54,116172909676.84,126460287749.96,171006767141.21,210607450227.13,225833007897.79

### **3.3. tab_stat_gdp_221116**

In [9]:
stat('gdp')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,73,164602950835.86,17634197003.8,117182256504.75,155237023534.17,173142353556.2,177540070836.86,184658507921.31
1,Australia,AUS,251,244951404886.35,135465144034.75,63438748459.13,131049633281.42,208801129428.12,355144518739.88,521869770433.28
2,Austria,AUT,110,71666559144.28,8913066271.44,54248461314.0,64583817898.94,73887626126.48,77818356577.88,86719344175.22
3,Belgium,BEL,109,87158446958.65,11288842566.35,66247540099.96,77475238386.27,89396074408.01,96241736510.31,106359690040.39
4,Bulgaria,BGR,109,17144981939.38,3696992518.38,10953855039.11,13401457069.55,18454303882.01,19820856595.87,23007853116.44
5,Brazil,BRA,105,252960404374.76,46218766509.85,177228358269.44,206261794881.6,263188375149.1,296416585266.2,311657759638.4
6,Canada,CAN,246,296084385327.94,133389379990.28,86207950975.6,185977867068.61,272051205071.47,421971005570.53,539270943440.33
7,Switzerland,CHE,169,135044264592.26,29734083244.01,92377624484.42,114023529586.72,131391150682.99,160447724083.71,192710649871.06
8,Chile,CHL,106,35265813465319.47,9589986382098.2,19961719114956.12,25718032515311.01,34801567532631.25,44022306662217.29,52687507073438.76
9,Colombia,COL,69,182420954004061.28,30778418110485.88,125574557817457.1,152236404011885.5,188542644961607.9,207749386974017.7,235485797461579.6
10,Cyprus,CYP,109,4315060580.87,821841601.72,2822174830.56,3689392641.11,4447020512.47,4870735700.91,5775677462.98
11,Czech Republic,CZE,105,954149848873.49,181000622373.94,688278090243.32,764749548616.72,996192621235.44,1088853238907.86,1262216360399.75
12,Germany,DEU,126,627001176655.56,73829033524.91,508918426439.0,562418506606.45,616666759945.74,687514505228.94,760857301503.43
13,Denmark,DNK,109,454979246452.31,48815812206.91,358665828280.47,424004735413.41,457229550729.2,482383544824.2,563683364172.78
14,Spain,ESP,110,249718718592.26,33631344007.91,176142207842.35,229145073257.59,260013693379.42,274119948255.42,306332500223.32
15,Estonia,EST,109,3729251940.56,992272109.22,1923023589.14,2851790956.4,3923130235.14,4400584085.94,5537718454.09
16,Finland,FIN,130,42244532259.73,7818960880.11,28254343277.08,35163367239.52,45431672572.81,48254526119.12,53037613323.33
17,France,FRA,170,429316384525.81,90029055433.18,279251900901.26,358932947262.92,448692021591.91,509573914561.2,581923822312.72
18,United Kingdom,GBR,270,320843289836.36,136989573403.13,122338437898.72,205255457341.69,313446423691.44,459016655123.17,583947792182.42
19,Greece,GRC,109,50907628465.48,7181769534.49,40874000002.24,45836123622.83,47573662821.55,56743560295.13,66278486896.26
20,"Hong Kong SAR, China",HKG,129,497557953040.58,150790023958.27,257327668995.13,360481380415.89,499778470918.76,645865439472.05,731964679223.14
21,Croatia,HRV,109,78618202315.29,11409756595.64,53666269108.08,67636153763.35,81653224114.24,86903570407.37,98621216800.59
22,Hungary,HUN,109,6870755701883.97,1242744999039.52,4805458763365.21,5876102084108.06,6949513841069.29,7568491112390.92,9513070093498.98
23,Indonesia,IDN,90,1859805509898300.2,598177322277223.0,1013677616104484.0,1305553737672015.2,1795455149430395.0,2391720731661034.0,2896892682330298.0
24,India,IND,104,20059933434519.59,9608127312353.12,7909283190903.63,10757145070326.49,17704252478012.43,28201419625243.2,37793145201546.8
25,Ireland,IRL,109,45232277828.29,17599158763.89,19780987553.72,33443141479.41,41879162069.61,55499298097.2,93147372446.13
26,Israel,ISR,110,240706343033.31,71156728983.62,136462233812.15,180190393864.94,229817786610.95,295007073115.54,397077711821.0
27,Italy,ITA,106,394695753973.91,16621547282.97,348602523529.84,386693787617.8,397816275372.66,404720189877.94,426352592658.79
28,Japan,JPN,114,127028948585113.1,7469124719513.64,111107680956074.1,120748836964888.45,128062714005653.31,133209909692635.38,140637000178012.1
29,"Korea, Rep.",KOR,250,173248417553004.12,156581500537744.8,7127459256171.3,29651514256425.22,122867641895887.94,308286641407506.75,490179887933458.6
30,Lithuania,LTU,110,7011487094.87,2025712614.65,3568815327.5,5019325721.53,7226606511.59,8463241023.41,10551688321.82
31,Luxembourg,LUX,109,10030756662.91,2291760293.87,5857311347.75,8342316303.35,10511422821.8,11805554502.49,14144288616.94
32,Latvia,LVA,109,4527589188.8,1180914934.33,2397095906.9,3391613917.59,4829188992.79,5533122974.35,6250536761.79
33,Mexico,MEX,118,3630775482720.12,654262748446.59,2466708580282.31,3193262240241.66,3650483797718.22,4229560855228.0,4775401736645.74
34,Malta,MLT,89,1915774864.68,529864900.7,1309589293.37,1475993027.87,1711252931.79,2315208181.4,2999061066.28
35,Netherlands,NLD,106,155772096619.18,18167477663.72,114809959095.9,143206002584.28,159759060143.72,166214961393.41,191546164373.43
36,Norway,NOR,178,528365037162.59,154492205874.41,272565838194.54,379418186856.07,553881889398.9,656070620148.28,790033704283.08
37,New Zealand,NZL,140,43863347677.61,12777589166.3,26663476199.28,32662575551.17,44090020696.49,52255609848.76,70334592973.77
38,Poland,POL,109,340986059937.79,99000701585.3,185302534916.86,250380242077.84,339268575351.34,414834078378.71,542283776631.85
39,Portugal,PRT,109,42802351685.04,3311672079.66,33727493338.34,41955664890.47,43284887960.89,44890533440.35,49338272058.24
40,Romania,ROU,110,130045777467.42,34412094987.2,84571507557.88,93949739900.42,133474215357.87,151991104009.98,196369577401.85
41,Russian Federation,RUS,75,20042176731045.11,2513033442581.4,13984915247863.92,18835378667653.84,21198633205483.77,21747496437537.69,23228634118989.06
42,Singapore,SGP,186,51010448453.96,36536769636.15,7495895457.54,16549404938.83,42547646957.0,77323149344.54,122886339943.95
43,Slovak Republic,SVK,110,15547025546.99,4250534540.12,8627115689.1,11084740610.35,16520668159.24,19461410657.64,22014733733.05
44,Slovenia,SVN,110,8575987183.94,1583189396.97,5659442255.09,7285259480.38,8948780640.18,9559832010.8,11946178114.78
45,Sweden,SWE,117,841788964640.53,164981180632.63,550178623627.68,719332104420.65,858450585383.06,964838339847.11,1127323426285.43
46,Thailand,THA,76,2174881783136.14,366712927602.52,1463883167321.28,1887387879921.31,2212262538248.64,2503810109426.54,2784796452286.65
47,Turkiye,TUR,97,323067163278.99,111155859176.31,181196950322.45,220603362364.25,288011902787.12,418884081645.44,556904423102.71
48,United States,USA,290,2329753540154.74,1329751924118.45,554177899660.66,1182728556475.13,2046148306012.44,3576459439261.24,4942887823680.12
49,South Africa,ZAF,117,895734417004.83,195183687104.75,573343478430.49,703141645257.71,951960552904.42,1091193493231.5,1189699830843.84

### **3.4. tab_stat_reer_221116**

In [10]:
stat('reer')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,114,135.86,73.99,52.01,78.24,107.71,227.29,281.92
1,Australia,AUS,170,86.7,11.02,67.12,77.04,87.49,94.29,110.51
2,Austria,AUT,174,101.44,3.4,93.93,99.08,101.72,103.3,111.76
3,Belgium,BEL,174,100.66,4.82,91.85,98.07,100.62,102.5,120.9
4,Bulgaria,BGR,118,84.5,19.67,41.5,69.1,93.93,100.77,110.07
5,Brazil,BRA,170,82.22,16.73,48.66,69.72,81.4,95.58,120.85
6,Canada,CAN,174,90.55,10.24,71.69,81.91,91.78,99.58,109.4
7,Switzerland,CHE,174,97.45,6.92,81.54,92.57,96.43,103.56,115.46
8,Chile,CHL,170,105.0,24.66,82.79,91.46,97.11,105.57,203.52
9,Colombia,COL,170,92.79,24.66,63.34,75.16,84.82,100.08,161.85
10,Cyprus,CYP,170,95.85,6.45,82.24,90.44,94.46,101.62,112.04
11,Czech Republic,CZE,130,80.47,19.63,39.1,64.55,87.04,98.44,114.16
12,Germany,DEU,174,104.65,7.24,91.46,98.8,104.83,108.32,122.31
13,Denmark,DNK,174,95.82,4.46,84.43,94.07,96.41,98.71,105.13
14,Spain,ESP,170,95.1,6.87,76.07,90.46,95.56,99.62,109.46
15,Estonia,EST,114,92.31,15.21,44.15,83.15,99.29,102.78,116.91
16,Finland,FIN,174,109.66,12.58,93.86,99.53,105.58,118.82,142.85
17,France,FRA,170,102.96,6.51,89.9,96.84,103.9,107.37,120.06
18,United Kingdom,GBR,174,116.31,12.97,95.64,103.46,116.45,126.96,151.66
19,Greece,GRC,170,89.27,7.1,70.82,85.34,89.7,95.67,101.97
20,"Hong Kong SAR, China",HKG,114,120.12,15.83,93.07,106.62,119.02,127.65,161.96
21,Croatia,HRV,114,94.18,3.77,86.62,92.22,93.84,96.14,103.92
22,Hungary,HUN,127,84.55,13.06,53.66,71.77,88.51,94.28,111.02
23,Indonesia,IDN,114,88.36,12.94,41.66,83.66,89.99,95.64,112.77
24,India,IND,114,94.71,4.99,84.45,91.26,94.07,99.31,103.89
25,Ireland,IRL,174,95.66,7.51,81.24,89.21,96.23,101.09,115.74
26,Israel,ISR,174,102.89,7.47,85.27,98.57,103.57,108.11,117.78
27,Italy,ITA,170,100.66,7.0,84.97,95.56,99.22,103.28,119.99
28,Japan,JPN,170,96.04,18.83,60.47,78.21,98.62,108.62,149.05
29,"Korea, Rep.",KOR,114,109.46,10.74,76.62,102.23,108.35,113.75,131.7
30,Lithuania,LTU,114,90.71,16.76,41.04,87.92,96.66,101.35,114.59
31,Luxembourg,LUX,174,99.96,3.19,92.68,98.74,99.97,101.2,112.0
32,Latvia,LVA,118,91.45,12.59,54.25,84.52,95.28,101.18,110.12
33,Mexico,MEX,170,98.34,15.87,63.36,85.2,99.13,109.23,141.63
34,Malta,MLT,174,98.94,8.87,85.28,91.96,96.71,103.33,122.58
35,Netherlands,NLD,174,100.45,3.72,91.57,97.54,99.93,102.83,114.24
36,Norway,NOR,174,94.78,6.35,75.89,91.65,96.09,99.7,105.48
37,New Zealand,NZL,174,94.41,10.52,72.27,85.27,95.58,103.23,114.96
38,Poland,POL,127,88.73,13.35,43.45,83.13,92.55,97.35,118.0
39,Portugal,PRT,174,91.94,10.34,68.75,82.31,96.01,99.01,105.15
40,Romania,ROU,127,86.7,18.03,32.42,76.28,96.14,99.77,116.24
41,Russian Federation,RUS,114,80.87,16.94,45.38,70.38,81.64,93.4,109.83
42,Singapore,SGP,174,100.37,7.42,82.97,95.3,100.35,106.89,112.83
43,Slovak Republic,SVK,130,77.35,23.17,41.09,52.83,79.5,100.08,105.1
44,Slovenia,SVN,114,97.16,2.86,84.43,96.05,97.48,98.85,102.82
45,Sweden,SWE,174,114.91,18.16,84.37,102.64,112.79,128.61,152.94
46,Thailand,THA,114,98.43,9.37,77.39,90.96,100.23,105.33,118.89
47,Turkiye,TUR,114,76.01,15.23,44.19,62.88,78.59,88.38,102.23
48,United States,USA,170,112.75,12.37,93.38,103.85,111.21,117.65,157.58
49,South Africa,ZAF,174,109.52,29.76,64.56,83.24,103.7,126.07,186.92

### **3.5. tab_stat_ca_221116**

In [11]:
stat('ca')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,73,-0.33,2.5,-6.17,-2.38,-0.18,1.81,3.8
1,Australia,AUS,250,-3.0,2.2,-7.28,-4.56,-3.2,-1.97,4.23
2,Austria,AUT,154,-0.16,2.04,-4.9,-1.48,-0.3,0.99,4.54
3,Belgium,BEL,134,2.17,2.29,-3.54,0.65,2.78,4.0,5.9
4,Bulgaria,BGR,109,-3.64,7.52,-27.11,-5.66,-1.0,1.14,10.13
5,Brazil,BRA,105,-2.07,1.87,-4.9,-3.62,-2.58,-0.93,1.83
6,Canada,CAN,245,-1.75,1.9,-4.85,-3.15,-2.26,-0.4,3.49
7,Switzerland,CHE,149,7.17,3.47,-3.4,4.81,6.5,9.9,14.54
8,Chile,CHL,103,-1.37,3.05,-7.47,-3.61,-1.74,0.45,6.15
9,Colombia,COL,70,-3.61,1.5,-6.82,-4.38,-3.51,-2.49,-1.01
10,Cyprus,CYP,28,-2.58,1.52,-6.14,-3.25,-2.55,-1.9,0.88
11,Czech Republic,CZE,109,-2.12,2.66,-8.05,-4.08,-2.05,-0.13,6.34
12,Germany,DEU,125,3.64,3.83,-2.11,-0.78,5.14,7.0,9.09
13,Denmark,DNK,134,-0.36,2.78,-5.9,-2.88,0.16,2.07,4.3
14,Spain,ESP,134,-2.56,2.76,-10.47,-3.74,-2.25,-0.71,2.24
15,Estonia,EST,109,-4.36,6.13,-17.71,-9.58,-4.25,1.35,5.26
16,Finland,FIN,134,0.81,4.27,-9.12,-2.22,0.53,4.4,8.78
17,France,FRA,134,0.34,1.52,-4.8,-0.69,0.35,1.25,4.19
18,United Kingdom,GBR,249,-1.58,1.85,-5.98,-2.86,-1.24,-0.27,2.95
19,Greece,GRC,81,-6.66,4.73,-16.66,-9.64,-6.97,-2.38,1.69
20,"Hong Kong SAR, China",HKG,93,5.81,3.69,0.03,2.96,5.12,8.78,14.95
21,Croatia,HRV,109,-3.29,4.69,-14.89,-7.1,-3.16,0.61,7.97
22,Hungary,HUN,109,-3.15,4.33,-10.27,-7.23,-4.03,0.64,5.02
23,Indonesia,IDN,74,-0.59,1.94,-3.61,-2.38,-0.42,0.68,3.9
24,India,IND,104,-1.22,1.71,-6.07,-2.05,-1.13,-0.46,3.08
25,Ireland,IRL,82,-1.54,11.13,-47.76,-5.32,-0.93,1.91,30.22
26,Israel,ISR,109,1.42,2.93,-5.29,-0.69,2.18,3.81,6.55
27,Italy,ITA,150,-0.28,1.62,-4.89,-1.36,-0.45,1.01,3.23
28,Japan,JPN,162,2.03,1.41,-1.75,1.11,2.27,2.93,5.05
29,"Korea, Rep.",KOR,170,1.3,4.33,-11.46,-1.01,1.52,4.21,12.32
30,Lithuania,LTU,73,-2.38,5.95,-16.32,-6.19,-0.83,1.07,8.71
31,Luxembourg,LUX,109,6.74,6.02,-11.35,3.17,7.46,11.05,22.95
32,Latvia,LVA,89,-4.56,7.34,-24.49,-7.27,-3.16,-0.16,11.08
33,Mexico,MEX,117,-1.54,1.58,-6.04,-2.39,-1.47,-0.56,5.45
34,Malta,MLT,32,-2.01,2.1,-6.1,-2.99,-2.1,-0.62,1.32
35,Netherlands,NLD,76,8.03,2.33,-1.85,6.75,7.85,9.57,13.15
36,Norway,NOR,165,6.91,6.23,-9.25,2.71,6.19,11.98,23.17
37,New Zealand,NZL,140,-3.57,1.89,-8.82,-4.32,-3.32,-2.36,0.99
38,Poland,POL,89,-2.98,2.58,-7.59,-4.98,-3.02,-1.43,3.43
39,Portugal,PRT,105,-5.25,4.7,-12.65,-9.61,-6.64,-0.4,2.09
40,Romania,ROU,109,-5.47,3.25,-14.97,-7.04,-5.11,-3.4,1.34
41,Russian Federation,RUS,75,4.93,2.77,0.97,2.67,4.66,6.72,11.44
42,Singapore,SGP,106,17.49,4.57,6.97,14.59,16.42,19.17,32.61
43,Slovak Republic,SVK,73,-3.29,3.55,-11.76,-5.81,-3.12,-1.29,3.89
44,Slovenia,SVN,109,0.7,3.65,-8.24,-1.61,-0.2,4.07,8.6
45,Sweden,SWE,117,4.55,2.03,-2.51,3.46,4.5,5.79,8.7
46,Thailand,THA,116,2.51,5.67,-9.86,-1.09,3.23,6.83,13.51
47,Turkiye,TUR,97,-3.26,2.73,-9.52,-5.23,-3.45,-1.84,3.23
48,United States,USA,249,-1.65,1.84,-6.24,-2.88,-1.7,0.07,1.18
49,South Africa,ZAF,249,-1.02,3.19,-9.37,-3.42,-1.15,1.06,7.95

### **3.6. tab_stat_pcon_221116**

In [12]:
stat('pcon')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,74,115116532010.27,16965413733.73,75994731834.28,104799200815.84,121797166192.9,128612809847.99,138580481579.11
1,Australia,AUS,252,131513245532.67,74920755764.87,33920849243.57,70877371342.15,109857888163.8,195366330197.24,278948785264.22
2,Austria,AUT,110,37773656973.27,3661881537.67,30198755849.78,34786530122.59,38736218742.37,40494247601.97,43707524965.75
3,Belgium,BEL,110,45191662718.88,5078693466.74,36088915590.46,41306941368.98,45024670451.42,49232041421.79,55167305540.21
4,Bulgaria,BGR,110,10831240640.7,2944067030.76,5645615973.17,8176297703.99,11916277811.28,12790683259.43,16316798278.78
5,Brazil,BRA,106,164168153890.74,34958653126.23,113464645451.77,126088755842.04,167059432135.0,199461341709.58,210824240923.65
6,Canada,CAN,166,196784106502.2,64110105772.18,105872216339.13,139208811609.94,185853168059.25,254036054783.33,316603506604.59
7,Switzerland,CHE,170,73124928874.67,13777351319.98,51888870248.31,62506706804.62,73205763755.28,85079695878.74,97272292712.13
8,Chile,CHL,106,20261008898065.97,7100941863177.08,10392472358831.4,13083892041881.26,18663390418058.76,26424593515879.98,35523950528014.89
9,Colombia,COL,70,126979067289470.06,24578275889888.93,85006131029725.89,104483041036763.31,129235627144337.77,143094580722232.66,185477540921958.3
10,Cyprus,CYP,110,2732128273.92,597246119.33,1622247266.39,2209435028.35,2886613251.98,3197782064.83,3658557515.07
11,Czech Republic,CZE,106,465929241847.27,77733729031.47,335666743397.12,391236365230.26,485501288016.38,523846562470.38,600625273284.2
12,Germany,DEU,126,350279095117.21,29197260702.86,294503642560.34,330575057652.95,349100666308.63,368700560125.31,412860083507.34
13,Denmark,DNK,110,212839508991.01,22844661850.36,171374597566.95,189538161584.14,216657655526.3,226254701436.94,261007140398.07
14,Spain,ESP,110,142660905238.67,17043235825.16,104485960909.41,132960499164.34,147825887360.07,155335376521.87,167156312763.91
15,Estonia,EST,110,1965185264.91,584709281.09,892587814.94,1427529906.83,2046650547.05,2385844300.69,3026102336.7
16,Finland,FIN,130,22040893874.7,4253555317.41,14613373344.32,17999936463.52,23260108123.78,25645564848.67,28181115719.21
17,France,FRA,170,230943752272.7,48518906291.39,149864034620.37,192527724699.48,235930222484.8,276783969678.86,311322116657.16
18,United Kingdom,GBR,110,293874616879.36,44320492577.6,201515611987.18,264807249934.58,298829110907.44,324769994408.47,377324739208.19
19,Greece,GRC,110,33781227764.33,4522465999.64,26778551279.74,30722298325.57,32091897663.91,36991625344.4,43740049068.42
20,"Hong Kong SAR, China",HKG,130,321695336342.03,100394513203.56,161712936053.51,243648613402.99,290514280308.71,414827483621.87,507992441218.16
21,Croatia,HRV,110,46699945486.01,6565071129.96,32850175014.25,41487518738.64,48498717461.34,50543598697.74,59045617577.25
22,Hungary,HUN,110,3665325094954.28,624198036547.76,2558369570391.95,3252982048725.3,3678764497401.75,3972795644604.31,5180325417974.82
23,Indonesia,IDN,90,1052373313265590.4,302033236952118.25,628641281497137.5,781427196311828.1,1000150231166773.5,1327107393968624.5,1559219424873803.0
24,India,IND,105,11458419931140.51,5492962199672.28,4801182569172.9,6357701260659.83,10075868684252.87,16023088858553.29,23689669109607.36
25,Ireland,IRL,110,18006245399.93,3944617584.92,9357189120.36,15480151831.18,19537289964.79,20683301239.7,24026124240.83
26,Israel,ISR,110,127044515414.6,36978273430.69,68792735375.31,97133658367.93,123245106768.96,156848000588.17,202731586784.56
27,Italy,ITA,106,234997961999.21,10411147641.88,205829513905.13,230086918630.89,236606429399.14,242587674756.42,249886373594.41
28,Japan,JPN,114,70788500697865.89,3969741630864.25,61946153996353.84,67874917938876.45,71874100695452.53,73984139397839.12,76788477069850.69
29,"Korea, Rep.",KOR,250,93396176047598.4,74258973643198.9,7277341902154.85,23118665351585.08,74488765231640.5,164522744788509.53,227524553024684.8
30,Lithuania,LTU,110,4480334012.26,1368938760.77,2133373823.56,3092758504.09,4722516371.55,5591144710.86,6790372571.62
31,Luxembourg,LUX,110,3485945447.95,698827230.23,2192876458.88,2975644246.66,3471953312.11,4036835415.97,4746603509.23
32,Latvia,LVA,110,2784960049.97,710879387.04,1504937926.74,2000540001.97,2904147528.14,3402109421.23,3806287646.62
33,Mexico,MEX,118,2413929888644.62,482761958040.93,1546759439789.53,2091555370608.42,2501666314263.76,2771435145664.22,3233338488105.95
34,Malta,MLT,90,1059512217.89,176941276.34,815770839.92,935401876.57,1032195886.77,1177937378.34,1457982763.26
35,Netherlands,NLD,106,71109614864.55,4963985059.01,55931978864.77,70787281570.99,72035910685.87,73182315642.2,80606253187.51
36,Norway,NOR,178,207957715480.72,74417699885.92,108746794789.88,141042449324.04,193199691490.94,276482634653.43,350524521165.74
37,New Zealand,NZL,141,25843371300.72,8502671911.55,15122831913.21,18384849465.23,25299699041.22,31484570665.29,43983541510.72
38,Poland,POL,110,207422989681.33,53706080820.53,111873250544.4,160663593054.6,212317761583.03,245371956722.1,313059968093.22
39,Portugal,PRT,110,27511563359.81,2414554390.89,21296803874.24,26625602619.36,27880194695.35,29100588704.73,32006229414.04
40,Romania,ROU,110,80359033025.97,30478197756.86,39203796843.37,47594736590.04,85233464209.49,96667075849.66,139219736439.85
41,Russian Federation,RUS,75,10578013359071.48,2120211300313.45,5622260149418.08,9713371931929.91,11407202519462.79,12172700182301.74,13053650815444.78
42,Singapore,SGP,186,20810423805.14,12790079600.22,4558230230.06,8011168208.93,17605198795.92,31654781986.87,47055156759.35
43,Slovak Republic,SVK,110,8681141340.99,2014148335.65,5095859302.74,6734268086.82,9478721793.69,9945449926.38,12101666133.45
44,Slovenia,SVN,110,4698144911.84,760815975.3,3285512517.33,4065023080.52,4889858136.82,5146334969.61,6696929404.44
45,Sweden,SWE,118,392360556333.64,78636378025.86,270036729480.83,333660108297.89,395983172520.76,460256041139.24,542352185955.39
46,Thailand,THA,76,1153649703579.39,170615323695.17,837036089342.19,1012911924544.63,1169779109779.29,1288372615692.54,1434900989060.8
47,Turkiye,TUR,54,248321987291.8,51118959205.45,159781260423.54,209741239286.62,248210283229.57,273864470131.15,387728726466.3
48,United States,USA,290,1540190260801.7,938620538662.17,355889414656.99,714926535101.5,1316898370918.0,2418522060786.12,3479294693075.92
49,South Africa,ZAF,118,559732244016.26,143027145363.22,322071036448.74,418792593933.71,592816837261.56,692003933699.0,778076359011.2

### **3.7. tab_stat_cds_221116**

In [13]:
stat('cds')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,90,1272.44,1316.66,72.0,402.61,693.08,1554.46,5454.63
1,Australia,AUS,86,28.72,28.25,2.0,4.0,23.16,39.84,141.98
2,Austria,AUT,70,38.29,43.01,2.14,11.63,24.68,41.85,191.04
3,Belgium,BEL,78,48.95,65.82,2.54,7.31,27.62,49.94,320.66
4,Bulgaria,BGR,98,221.42,196.15,29.48,83.26,164.17,308.42,819.17
5,Brazil,BRA,102,427.95,526.89,76.92,160.13,246.27,494.41,3967.5
6,Canada,CAN,39,31.35,4.07,21.1,29.74,31.96,33.34,43.7
7,Switzerland,CHE,54,28.97,18.02,6.77,12.79,27.46,41.45,77.69
8,Chile,CHL,82,84.27,52.41,14.66,48.23,75.85,97.45,232.04
9,Colombia,COL,98,296.01,234.6,74.49,125.02,171.31,451.23,880.83
10,Cyprus,CYP,58,360.98,388.8,37.31,110.33,162.18,461.85,1535.29
11,Czech Republic,CZE,82,58.78,39.2,7.46,39.74,48.03,72.0,177.75
12,Germany,DEU,78,23.0,23.08,4.25,10.42,14.56,25.74,114.44
13,Denmark,DNK,62,32.75,30.96,8.84,12.65,24.31,36.38,149.93
14,Spain,ESP,74,107.52,120.5,3.26,34.88,68.14,114.68,531.06
15,Estonia,EST,58,123.12,118.17,53.93,66.17,70.84,105.64,448.13
16,Finland,FIN,62,26.86,16.9,4.06,15.38,24.5,32.83,82.76
17,France,FRA,78,37.03,41.92,2.53,5.66,23.65,50.39,196.21
18,United Kingdom,GBR,58,41.59,23.92,10.81,22.1,33.78,61.77,100.17
19,Greece,GRC,86,1316.12,3617.84,8.0,39.4,184.15,957.73,26089.2
20,"Hong Kong SAR, China",HKG,62,43.83,18.12,10.08,36.18,43.98,51.32,96.37
21,Croatia,HRV,98,229.34,172.34,29.29,87.74,174.8,338.96,652.7
22,Hungary,HUN,98,138.44,132.82,18.67,35.83,89.71,185.98,645.0
23,Indonesia,IDN,90,350.03,354.4,68.66,137.58,184.27,358.15,1275.29
24,India,IND,35,130.09,53.94,69.68,87.64,107.09,170.74,294.16
25,Ireland,IRL,66,135.76,206.33,2.0,19.15,46.0,145.22,781.79
26,Israel,ISR,74,82.59,45.36,22.63,51.3,73.35,105.58,203.61
27,Italy,ITA,78,134.23,115.65,6.6,25.42,128.04,173.67,511.22
28,Japan,JPN,86,38.52,31.52,3.33,18.86,26.12,49.99,147.55
29,"Korea, Rep.",KOR,90,101.92,130.55,18.29,39.07,56.92,102.5,629.89
30,Lithuania,LTU,74,118.09,111.65,5.88,53.2,70.02,167.47,474.58
31,Luxembourg,LUX,nan,nan,nan,nan,nan,nan,nan,nan
32,Latvia,LVA,66,168.1,181.24,6.5,60.57,81.8,221.93,692.68
33,Mexico,MEX,102,177.69,118.69,36.26,106.97,133.92,196.67,544.36
34,Malta,MLT,nan,nan,nan,nan,nan,nan,nan,nan
35,Netherlands,NLD,58,36.09,27.54,10.59,15.12,27.72,52.46,123.5
36,Norway,NOR,54,19.35,8.55,11.12,13.45,16.68,22.99,52.84
37,New Zealand,NZL,58,45.23,25.43,16.35,23.74,37.34,62.01,115.85
38,Poland,POL,102,80.2,52.95,14.2,47.08,69.88,100.89,299.25
39,Portugal,PRT,78,188.06,261.46,6.22,13.76,78.65,248.06,1141.19
40,Romania,ROU,82,186.3,121.41,33.87,98.58,133.82,276.17,456.43
41,Russian Federation,RUS,102,881.25,2041.76,54.64,132.22,207.25,466.81,8780.28
42,Singapore,SGP,nan,nan,nan,nan,nan,nan,nan,nan
43,Slovak Republic,SVK,86,66.99,55.43,7.42,39.26,50.42,87.72,310.4
44,Slovenia,SVN,70,111.5,104.84,4.38,66.42,81.87,113.62,411.02
45,Sweden,SWE,74,20.91,17.95,1.77,10.72,16.17,28.84,80.5
46,Thailand,THA,90,116.54,120.12,26.64,44.2,93.34,135.33,606.0
47,Turkiye,TUR,98,398.28,261.44,129.7,201.44,300.5,492.09,1329.38
48,United States,USA,54,29.53,12.63,11.43,19.92,25.98,39.14,61.0
49,South Africa,ZAF,98,197.66,91.37,29.86,146.04,197.33,217.91,426.41

### **3.8. tab_stat_inv_221116**

In [14]:
stat('inv')

,country,isocode,obs,mean,std,min,25th,median,75th,max
0,Argentina,ARG,74,31658398707.85,5663744472.51,18276952085.45,27378902279.35,33243117441.98,35602204311.72,40682679704.74
1,Australia,AUS,252,54137728506.71,37672419341.14,10214085960.84,21550024778.65,39323422421.44,88974942967.53,123957572579.17
2,Austria,AUT,110,17077173639.52,2114863522.71,13520458605.18,15768284432.45,16653041559.69,17897095198.69,22567666958.14
3,Belgium,BEL,110,20145100147.27,3493799656.67,14290691828.23,16926264279.0,20406259571.12,22742594953.05,26945091989.58
4,Bulgaria,BGR,110,3407081547.91,1425251533.16,99169691.68,2185389230.91,3997821150.94,4277291556.48,6350982440.74
5,Brazil,BRA,106,49596265016.78,11235351777.25,34778161660.08,39048900256.65,49587395178.24,59973177537.77,71090166182.46
6,Canada,CAN,246,60798985727.11,32944503715.53,14689814486.99,34092443374.15,52016330045.59,96957488542.48,119043828306.9
7,Switzerland,CHE,170,34253318381.25,8821085749.13,20185464027.68,27455390968.51,33737198404.01,41283706391.77,49419719950.46
8,Chile,CHL,106,7859189480611.64,3114184714841.24,3377505462505.99,4306444800365.04,8253866821493.54,10799731657952.27,12955939417501.06
9,Colombia,COL,70,38228044438210.68,8150171902800.64,20483823422813.55,30998916864319.34,39193725170206.04,45829943485129.01,51098626745875.12
10,Cyprus,CYP,110,893677941.41,230472127.66,339561707.9,720232829.67,834832392.77,1099306869.46,1443888718.51
11,Czech Republic,CZE,106,261441066256.84,47937413978.56,184214336703.52,216277582128.32,267235511998.87,295777213829.37,348770244179.8
12,Germany,DEU,126,128974518795.21,13894342617.9,110511264929.91,116662396293.55,126678835987.01,136959853625.53,159058148796.97
13,Denmark,DNK,110,91022951929.6,15917995500.95,61090044127.71,81145114337.64,86523130415.86,102649578704.36,128597728623.14
14,Spain,ESP,110,56980664285.26,10106830093.32,38008473782.95,50506840427.62,57109511120.83,62022002714.45,78033120443.25
15,Estonia,EST,110,1026667945.77,432646393.72,288592562.35,646413456.12,1108298304.55,1332507465.25,2404938528.09
16,Finland,FIN,130,9666108204.21,1938330477.49,5471884158.58,8741050804.31,10121579987.39,11099221710.28,12385790640.42
17,France,FRA,170,94793965391.68,22239373259.55,60145141498.73,77956624699.36,99307572825.78,112436116169.09,138053232927.43
18,United Kingdom,GBR,270,57608503921.51,23785800657.27,15112623091.56,39973868677.3,60181305422.02,77168594499.8,103945363450.93
19,Greece,GRC,110,8760073109.25,3481967676.47,4531365477.46,5213770538.01,7690500227.75,11442516262.41,17320151676.33
20,"Hong Kong SAR, China",HKG,nan,nan,nan,nan,nan,nan,nan,nan
21,Croatia,HRV,110,16981195272.86,3797378522.55,6716896434.38,14075377503.52,17545585897.51,19813541331.37,24830073775.2
22,Hungary,HUN,110,1542293909981.39,409820196773.31,859756090717.59,1306560570287.52,1507582658696.51,1673063103134.65,2472049179712.7
23,Indonesia,IDN,90,579207837082090.6,217171747799626.9,251014564662010.7,384333907646194.8,567007321880996.2,771026038111643.0,911484231855852.4
24,India,IND,105,6272006346936.22,3379296262324.28,1804969832762.35,2741522710542.58,5996795986522.44,8587682795942.1,13246309683652.42
25,Ireland,IRL,110,11633655017.89,9447619601.9,3508100026.25,6787969491.34,8387107187.19,11297039811.6,58044664557.29
26,Israel,ISR,110,54514386643.92,15018574412.39,37447576023.5,42254085143.12,48140938205.08,63084952056.22,92520672594.82
27,Italy,ITA,106,78069740513.09,8406175449.4,62310879328.3,70574723513.27,77816099028.23,85761474328.79,93522387134.78
28,Japan,JPN,114,34104195399273.08,2330816685044.6,29015057271934.59,32952004228640.12,34131402628534.54,35490101765526.76,39095243201791.22
29,"Korea, Rep.",KOR,250,54115091800259.38,47893025145125.59,412036977959.86,6205648415841.6,48843217752170.99,97203653946430.78,144112787591550.4
30,Lithuania,LTU,110,1399753625.33,558460419.75,410282158.16,899876258.22,1410672201.2,1841963483.9,2455084179.0
31,Luxembourg,LUX,110,1819810709.59,428998540.33,933498955.84,1509480205.53,1813027274.82,2185840071.43,2541576631.29
32,Latvia,LVA,110,1026571822.8,398511963.47,208582588.95,740067822.69,1119273424.15,1310631047.66,1817919309.56
33,Mexico,MEX,118,734990159845.78,151661826018.82,369677457557.83,613087967127.8,755370144024.68,868098842115.94,956530929235.23
34,Malta,MLT,90,395660113.64,150085577.54,166042682.43,282630755.82,325901819.76,557034013.86,719782544.32
35,Netherlands,NLD,106,33289707211.76,4954774601.62,22621655970.01,30170498205.73,31803601684.75,36978636501.35,51901811877.93
36,Norway,NOR,178,113898842495.38,39074155894.76,63078615876.75,78613250501.51,101968143533.92,153426470474.97,192435636837.74
37,New Zealand,NZL,141,9696976239.85,3904420382.2,4052663855.25,6384295158.92,9893340515.57,12348469016.37,17310223565.78
38,Poland,POL,110,66839705789.86,21896324243.4,26506044739.36,46777066590.53,71801538791.13,83904864256.54,104769855883.03
39,Portugal,PRT,110,8887348659.91,1374175536.88,6301522359.1,7771745203.12,9194798232.21,9856912013.73,11242702715.78
40,Romania,ROU,110,31766610218.73,13432574762.88,13411592558.68,16833410613.9,35817517596.39,42157763041.88,56936024408.39
41,Russian Federation,RUS,75,4455377064552.86,812134684916.5,2438304307659.28,4183857343990.18,4748561816340.85,5045646926614.28,5314482433795.41
42,Singapore,SGP,190,14038203234.82,9430165216.09,2001257108.4,5249561119.19,13190559100.52,21836032469.89,31164329603.1
43,Slovak Republic,SVK,110,3614002847.74,719079602.51,1935872368.97,3041514580.1,3665746243.31,4146391740.74,4943266540.96
44,Slovenia,SVN,110,1908625466.39,362654133.71,1170321842.91,1697304165.34,1852856879.03,2075490723.82,2955118090.67
45,Sweden,SWE,118,195600771003.3,52532285714.72,102635041074.6,158282880972.44,197287990898.72,232780660048.37,300456398846.0
46,Thailand,THA,78,543752110180.07,84317064680.46,337829786030.93,484805052938.6,556170330952.72,614239805324.78,657357948204.5
47,Turkiye,TUR,98,82514223416.04,36678099585.82,24918185529.87,50994642418.77,77935300860.8,117883960768.19,140398573371.02
48,United States,USA,202,581922863227.98,258268371687.44,216148074210.37,358253604799.79,549966663553.6,805741593943.27,1080778103445.87
49,South Africa,ZAF,118,143059425820.0,46772553610.39,64275803860.0,94098727512.04,158237448529.52,187731870353.21,203578869088.99

## **4. export the table**

In [15]:
# set the working directory

os.chdir('/content/gdrive/MyDrive/Colab Notebooks/RA1_data/table_221116')

In [16]:
# export the table

var_list = ['ggdebt', 'ggcon', 'gdp', 'reer', 'ca', 'pcon', 'cds', 'inv']

for k in range(0, len(var_list)):

    stat(var_list[k]).to_excel(excel_writer='tab_stat_{}'.format(var_list[k]) + '_221116.xlsx')